### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by ugurdogrusoz** [MuhamedKeta/2H.ChickenInvadersButPIRATES#1]
as 2H.\<project name\>

**Comment by MuhamedKeta** [comment]
Name changed to 2H.ChickenInvadersButPIRATES
Rather long but very original.

**Comment by ugurdogrusoz** [comment]
@MuhamedKeta thanks. You should assign the issue back to the creator when done though, so that they can verify and close. Keep that in mind for next time.
