### ISSUE TITLE
Create a Google doc for meeting logs

### ISSUE THREAD

**Issue by ugurdogrusoz** [MuhamedKeta/2H.ChickenInvadersButPIRATES#2]
and make sure the instructor and the TA has read access to it. Also make sure README.md has a link to it. You will update this doc as you meet.

**Comment by MuhamedKeta** [comment]
We have a .md file which I linked in the README. However we can make a google docs too if necessary.

**Comment by ugurdogrusoz** [comment]
It needs to be a Google doc please

**Comment by MuhamedKeta** [comment]
Is it okay now?

**Comment by ugurdogrusoz** [comment]
👍
